import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import { SearchProvider } from "./context/search_context";
import { CountriesWrapper } from "./context/countries_context";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeWrapper } from "./context/theme_context";
import { ToastContainer } from "react-toastify";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body className={inter.className}>
          <ThemeWrapper>
            <CountriesWrapper>
              <SearchProvider>
                <Navbar />
                {children}
                <ToastContainer />
              </SearchProvider>
            </CountriesWrapper>
          </ThemeWrapper>
        </body>
      </ClerkProvider>
    </html>
  );
}
